# all packages needed for scripts from Kayleigh H-T's sys map analysis, plus others Corey added

library(dplyr)
library(magrittr)
library(tidyverse)
library(maps)
library(bibliometrix)
library(ggplot2)
library(ggthemes)
library(ggpubr)
library(ggrepel)
library(plotly)
library(rphylopic)
library(png)
library(cowplot)
library(cartography)
library(sf)
library(data.table)
library(janitor)
library(reshape2)
library(splitstackshape)
library(cowplot)
library(patchwork)
library(forcats)